name: satellite_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*
  - gdal
  - mpi4py
  - python-dateutil
  - cdsapi
  - numpy
  - scipy
  - pandas
  - geopandas
  - jupyter
  - fiona
  - shapely
  - rasterio
  - rtree
  - xarray
  - netCDF4
  - cartopy
  - pyproj
  - jupyter
  - geopy
  - contextily
  - osmnx
  - wgrib2
  - cfgrib
  - leafmap
  