[datapaths]
home_root = "/Users/abdullah/OneDrive - King's College London/"
remote_root = "onedrive:"
data_root = "Datasets/WUI_Imagery/"

xBD_path = "xBD_Dataset/"
maxar_path = "Maxar/"

images_path = "fires/"
analysis_path = "Analysed_Images/"

main_csv_path = "Data/xBD_WUI_Analysis.csv"

[local_vars]
on_remote = false